export const ADD_ASSIGNMENT_REQUEST = 'ADD_ASSIGNMENT_REQUEST'
export const EDIT_ASSIGNMENT_REQUEST = 'EDIT_ASSIGNMENT_REQUEST'
export const GET_ASSIGNMENTS_REQUEST = 'GET_ASSIGNMENTS_REQUEST'
export const REMOVE_ASSIGNMENT_REQUEST = 'REMOVE_ASSIGNMENT_REQUEST'
